version: '3'

services:
  server:
    image: jstormes/loopback-world
    environment:
      XDEBUG_CONFIG: remote_host=docker.for.win.localhost remote_port=$XDEBUG_REMOTE_PORT
#      XDEBUG_CONFIG: remote_host=docker.for.mac.localhost remote_port=$XDEBUG_REMOTE_PORT
      MYSQL_PWD: naked
    networks:
      - net
    ports:
      - 443:443
      - 80:80
      # - 3306:3306
    volumes:
      - ./:/var/www
  bash:
    image: jstormes/loopback-world
    environment:
      MYSQL_PWD: naked
      MYSQL_DATABASE_NAME: $MYSQL_DATABASE_NAME
      COMPOSE_PROJECT_NAME: $COMPOSE_PROJECT_NAME
      EXTERNAL_MYSQL_PORT: $EXTERNAL_MYSQL_PORT
      XDEBUG_CONFIG: remote_host=docker.for.win.localhost remote_port=$XDEBUG_REMOTE_PORT
      PHP_IDE_CONFIG: serverName=auth
    volumes:
      - ./:/var/www
      - ./:/opt/project
#      - ./_ssh/:/root/ssh
#      - ./_docker/bash_scripts:/usr/local/sbin
    working_dir: /opt/project
    entrypoint: bash
networks:
  net:
    driver: bridge