<?php $this->layout('layout::default', ['title' => 'Home']) ?>

<div class="container">
    <div class="col-md-1">
        &nbsp;
    </div>
</div>

<!-- Error Notification -->
<?php if (!empty($this->data['error'])) : ?>
    <div class="container">
        <div class="col-md-1">
            &nbsp;
        </div>
        <div class="col-md-10">
            <div class="alert alert-danger" role="alert">
                <strong>Oh snap!</strong> <?php echo $this->data['error']; ?>
            </div>
        </div>
    </div>
<?php endif ?>

<!-- User Info -->
<form class="form-horizontal" action="<?php echo htmlspecialchars($_SERVER['REQUEST_URI']);?>" method="post">
    <input type="hidden" name="user_id" value="<?php echo $this->data['user']->getUserId(); ?>">

    <div class="well well-sm">
        <div class="form-group">
            <label for="user_name" class="col-md-2 control-label">user_name</label>
            <div class="col-md-9">
                <input type="email" name="user_name" class="form-control" id="user_name" placeholder="user_name" value="<?php echo $this->data['user']->getUserName(); ?>">
            </div>
        </div>
        <div class="form-group">
            <label for="password" class="col-md-2 control-label">password</label>
            <div class="col-md-9">
                <input type="password" name="password" class="form-control" id="password" placeholder="password">
            </div>
        </div>
        <div class="form-group">
            <label for="full_name" class="col-md-2 control-label">full_name</label>
            <div class="col-md-9">
                <input class="form-control" name="full_name" id="full_name" placeholder="full_name" value="<?php echo $this->data['user']->getFullName(); ?>">
            </div>
        </div>
        <div class="form-group">
            <label for="name_addressed_by" class="col-md-2 control-label">name_addressed_by</label>
            <div class="col-md-9">
                <input class="form-control" name="name_addressed_by" id="name_addressed_by" placeholder="name_addressed_by" value="<?php echo $this->data['user']->getNameAddressedBy(); ?>">
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-8">
                &nbsp;
            </div>
            <div class="col-md-4">
                <a class="btn btn-primary" href="/users">Cancel</a>
                <?php if ($this->data['is_new_user']) : ?>
                    <button type="submit" name="action" value="save" class="btn btn-primary" value="submit">Add User</button>
                <?php else : ?>
                    <button type="submit" name="action" value="save" class="btn btn-primary" value="submit">Update User</button>
                    <button type="submit" name="action" value="delete" class="btn btn-primary">Delete User</button>
                <?php endif ?>
            </div>
        </div>

    </div>
</form>

<!-- contact_methods -->
<form class="form-horizontal">
    <div class="well well-sm">
        <?php foreach ($this->data['user']->getPhone() as $phone) : ?>
        <div class="form-group">
            <label for="phone" class="col-md-2 control-label"><?php echo $phone->getType(); ?></label>
            <div class="col-md-4">
                <div class="input-group">
                    <input type="tel" class="form-control" placeholder="(555) 555-5555" value="<?php echo $phone->getPhoneNumber(); ?>" readonly>
                    <span class="input-group-btn">
                        <button class="btn btn-primary" type="button" data-toggle="modal" data-target="#phoneModal<?php echo $phone->getPhoneId(); ?>"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button>
                        <a class="btn btn-primary" href="skype:********?call"><i class="fa fa-skype" aria-hidden="true"></i></a>
                        <a class="btn btn-primary" href="tel:+1800229933"><i class="fa fa-phone" aria-hidden="true"></i></a>
                        <a class="btn btn-primary" href="sms:1-408-555-1212"><i class="fa fa-commenting-o" aria-hidden="true"></i></a>
                        <a class="btn btn-primary" href="mailto:1-408-555-1212"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                    </span>
                </div>
            </div>
        </div>
        <?php endforeach ?>

        <div class="form-group">
            <div class="col-md-8">
                &nbsp;
            </div>
            <div class="col-md-4">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#phoneModal">
                    Add contact_method
                </button>

            </div>
        </div>
    </div>

    <!-- Edit contact_method Modal -->
    <?php foreach ($this->data['user']->getPhone() as $phone) : ?>
    <div class="modal fade" id="phoneModal<?php echo $phone->getPhoneId(); ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Add Phone</h4>
                </div>
                <iframe src="/user/<?php echo $this->data['user']->getUserId(); ?>/phone/<?php echo $phone->getPhoneId(); ?>" width="100%" frameBorder="0"></iframe>
            </div>
        </div>
    </div>
    <?php endforeach ?>

    <!-- Add New contact_method Modal -->
    <div class="modal fade" id="phoneModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Add Phone</h4>
                </div>
                <iframe src="/user/2/phone" width="100%" frameBorder="0"></iframe>
            </div>
        </div>
    </div>

</form>


