<?php $this->layout('layout::default', ['title' => 'Home']) ?>

<div class="container">

    <div class="row">
        <div class="col-md-9">
        </div>
        <div class="col-md-3 pull-right">
            <form class="navbar-form" role="search">
                <div class="input-group add-on">
                    <input class="form-control" placeholder="Search" name="srch-term" id="srch-term" type="text">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            &nbsp;
        </div>
    </div>

    <div class="row pre-scrollable" style="max-height:60vh;">
        <div class="col-md-12">
            <table class="table table-hover">

                <thead>
                <tr>
                    <th>user_name</th>
                    <th>full_name</th>
                    <th>name_addressed_by</th>
                    <?php if ($this->data['isActionable']) : ?>
                        <th>&nbsp;</th>
                    <?php endif ?>
                </tr>
                </thead>

                <tbody>
                <?php foreach ($this->data['rows'] as $row) : ?>
                    <tr>
                        <td><?php echo $row->getUserName();?></td>
                        <td><?php echo $row->getFullName();?></td>
                        <td><?php echo $row->getNameAddressedBy();?></td>

                        <?php if ($this->data['isActionable']) : ?>
                            <td><a class="btn btn-primary" href="user/<?php echo $row->getUserId(); ?>">Edit</a></td>
                        <?php endif ?>
                    </tr>
                <?php endforeach ?>
                </tbody>

            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            &nbsp;
        </div>
    </div>

    <div class="row">
        <div class="col-md-9"></div>
        <div class="col-md-3 pull-right"><a class="btn btn-primary" href="user">Add New User</a></div>
    </div>

</div>