<?php $this->layout('layout::default', ['title' => 'Home']) ?>

<div class="container">
    <div class="col-md-1">
        &nbsp;
    </div>
</div>

<!-- Error Notification -->
<?php if (!empty($this->data['error'])) : ?>
    <div class="container">
        <div class="col-md-1">
            &nbsp;
        </div>
        <div class="col-md-10">
            <div class="alert alert-danger" role="alert">
                <strong>Oh snap!</strong> <?php echo $this->data['error']; ?>
            </div>
        </div>
    </div>
<?php endif ?>

<!-- User -->
<form class="form-horizontal" action="<?php echo htmlspecialchars($_SERVER['REQUEST_URI']);?>" method="post">
    <input type="hidden" name="user_id" value="<?php echo $this->data['user']->getUserId(); ?>">

    <div class="well well-sm">
        <div class="form-group">
            <label for="user_name" class="col-md-2 control-label">user_name</label>
            <div class="col-md-9">
                <input type="email" name="user_name" class="form-control" id="user_name" placeholder="user_name" value="<?php echo $this->data['user']->getUserName(); ?>">
            </div>
        </div>
        <div class="form-group">
            <label for="password" class="col-md-2 control-label">password</label>
            <div class="col-md-9">
                <input type="password" name="password" class="form-control" id="password" placeholder="password">
            </div>
        </div>
        <div class="form-group">
            <label for="full_name" class="col-md-2 control-label">full_name</label>
            <div class="col-md-9">
                <input class="form-control" name="full_name" id="full_name" placeholder="full_name" value="<?php echo $this->data['user']->getFullName(); ?>">
            </div>
        </div>
        <div class="form-group">
            <label for="name_addressed_by" class="col-md-2 control-label">name_addressed_by</label>
            <div class="col-md-9">
                <input class="form-control" name="name_addressed_by" id="name_addressed_by" placeholder="name_addressed_by" value="<?php echo $this->data['user']->getNameAddressedBy(); ?>">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-8">
                &nbsp;
            </div>
            <div class="col-md-4">
                <a class="btn btn-primary" href="/users">Cancel</a>
                <?php if ($this->data['is_new_user']) : ?>
                    <button type="submit" name="action" value="save" class="btn btn-primary" value="submit">Add User</button>
                <?php else : ?>
                    <button type="submit" name="action" value="save" class="btn btn-primary" value="submit">Update User</button>
                    <button type="submit" name="action" value="delete" class="btn btn-primary">Delete User</button>
                <?php endif ?>
            </div>

        </div>
    </div>
</form>

<!-- Phone -->
<form class="form-horizontal" action="<?php echo htmlspecialchars($_SERVER['REQUEST_URI']);?>" method="post">
    <div class="well well-sm">
        <?php foreach ($this->data['user']->getPhone() as $phone) : ?>
        <div class="form-group">
            <label for="phone" class="col-md-2 control-label"><?php echo $phone->getType(); ?></label>
            <div class="col-md-2">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="(555) 555-5555" value="<?php echo $phone->getPhoneNumber(); ?>">
                    <span class="input-group-btn">
                        <button class="btn btn-primary" name="delete-phone" value="" type="button">X</button>
                    </span>
                </div>
            </div>
        </div>
        <?php endforeach ?>

        <div class="form-group">
            <div class="col-md-8">
                &nbsp;
            </div>
            <div class="col-md-4">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#phoneModal">
                    Add Phone
                </button>

            </div>
        </div>
    </div>
</form>



<!-- Phone Modal -->
<div class="modal fade" id="phoneModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form class="form-inline" action="/user/2/phone" method="post">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Add Phone</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="new_phone_number" class="control-label">new_phone_number</label>&nbsp;
                        <input class="form-control" name="new_phone_number" id="new_phone_number" placeholder="(555) 555-5555" value="">
                    </div>
                    &nbsp;&nbsp;
                    <div class="form-group">
                        <label for="sel1" class="control-label">phone_type</label>&nbsp;
                        <?php $t=$this->data['user']->getPhone();
                        $t->current()->getTypes();?>
                        <select class="form-control" id="sel1">
                            <option>mobile</option>
                            <option>landline</option>
                        </select>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" name="action" value="add_phone" class="btn btn-primary">Add Phone</button>
                </div>
            </form>
        </div>
    </div>
</div>

