<?php
/**
 * Created by PhpStorm.
 * User: jstormes
 * Date: 11/30/17
 * Time: 7:38 PM
 */

namespace App\Model\HydratorStrategy;

use Zend\Hydrator\Strategy\DefaultStrategy;

class Phone extends DefaultStrategy
{
    public function __construct($adapter)
    {

    }

    public function hydrate($value)
    {
        return "hello";
        return parent::hydrate($value); // TODO: Change the autogenerated stub
    }

    public function extract($value)
    {
        return "hello";
        return parent::extract($value); // TODO: Change the autogenerated stub
    }
}