<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title><?=$this->e($title)?> - zend-expressive</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
    <style>
        body { padding-top: 60px; }
        .app { display: flex; min-height: 100vh; flex-direction: column; }
        .app-content { flex: 1; }
        .app-footer { padding-bottom: 1em; }
    </style>
</head>
<body class="app">

    <header class="app-header">
        <?=$this->section('header')?>
    </header>

    <div class="app-content">
        <main class="container">
            <?=$this->section('alert')?>
            <?=$this->section('content')?>
        </main>
    </div>

    <footer class="app-footer">
        <?=$this->section('footer')?>
    </footer>

</body>
</html>
