<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
                Oauth2
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a href="/users">
                        <i class="fa fa-users"></i> Users
                    </a>
                </li>
                <li>
                    <a href="https://docs.zendframework.com/zend-expressive/" target="_blank">
                        <i class="fa fa-book"></i> Docs
                    </a>
                </li>
                <li>
                    <a href="https://github.com/zendframework/zend-expressive" target="_blank">
                        <i class="fa fa-wrench"></i> Contribute
                    </a>
                </li>
                <li>
                    <a href="/api/ping">
                        Ping Test
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
